steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cogent-repository/$IMAGE_NAME:$SHORT_SHA'
  - '.'

# This step pushes the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cogent-repository/$IMAGE_NAME:$SHORT_SHA'

# Optionally, you can add steps to run tests or any other custom steps

options:
  logsBucket: 'gs://cogent-426809_cloudbuild'

