# Cloud Build YAML file
steps:
  # Build the Docker image (using a base image)
  - name: 'node:16'  # Replace 'node:16' with your desired base image
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cogent-426809/cogent-repository:$COMMIT_SHA', '.']



  # Push the Docker image to the Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cogent-426809/cogent-repository:$COMMIT_SHA']

# Specify the Docker image to use for the build
images:
  - 'us-central1-docker.pkg.dev/cogent-426809/cogent-repository:$COMMIT_SHA'

# Use the commit SHA as the Docker image tag
substitutions:
  _COMMIT_SHA: '${COMMIT_SHA}'

# Specify the logs bucket
logsBucket: 'gs://cogent-426809_cloudbuild/source'

