# Cloud Build YAML file
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cogent-426809/cogent-repository:$COMMIT_SHA', '.']

  # Push the Docker image to the Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cogent-426809/cogent-repository:$COMMIT_SHA']

# Specify the Docker image to use for the build
images:
  - 'us-central1-docker.pkg.dev/cogent-426809/cogent-repository:$COMMIT_SHA'

# Use the commit SHA as the Docker image tag
substitutions:
  _COMMIT_SHA: '${COMMIT_SHA}'

  options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

